-- 코드를 작성해주세요
SELECT 
    SUM(SCORE) AS SCORE,
    EMP.EMP_NO,
    EMP.EMP_NAME,
    EMP.POSITION,
    EMP.EMAIL
FROM
    HR_GRADE HR
LEFT JOIN 
    HR_EMPLOYEES EMP
    ON HR.EMP_NO = EMP.EMP_NO
WHERE 
    HR.YEAR = '2022'
GROUP BY HR.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;